- hosts:
    - localhost
  no_log: true
  vars_files:
    - ./config/users-configs.yml
    - ./config/servers.yml
    - ./config/supabase.yml
  pre_tasks:
    - name: Fetch configs UUIDs from Supabase
      delegate_to: localhost
      uri:
        url: "https://{{ config_supabase_project_id }}.supabase.co/rest/v1/configs?select=uuid"
        method: GET
        headers:
          apikey: "{{ config_supabase_api_key }}"
          Authorization: "Bearer {{ config_supabase_api_key }}"
      register: supabase_configs_response

    - name: Set user UUIDs fact
      delegate_to: localhost
      set_fact:
        config_local_configs: "{{ supabase_configs_response.json | map(attribute='uuid') | list }}"

    - name: Fetch users UUIDs from Supabase
      delegate_to: localhost
      uri:
        url: "https://{{ config_supabase_project_id }}.supabase.co/rest/v1/users?select=child_uuid"
        method: GET
        headers:
          apikey: "{{ config_supabase_api_key }}"
          Authorization: "Bearer {{ config_supabase_api_key }}"
      register: supabase_users_response

    - name: Set user UUIDs fact
      delegate_to: localhost
      set_fact:
        config_local_users: "{{ supabase_users_response.json | map(attribute='child_uuid') | list }}"
  roles:
    - role: users-configs
      vars:
        users_configs_default_redirect: "{{ config_users_configs_default_redirect }}"
        users_configs_servers: "{{ config_servers }}"
        users_configs_configs: "{{ config_local_configs }}"
        users_configs_users: "{{ config_local_users }}"
        users_configs_static_directory_filename: static
        users_configs_title: "{{ config_users_title }}"
        users_configs_support_url: "{{ config_users_support_url }}"
