- name: Ensure required variables are defined
  assert:
    that:
      - frontman_title is string
      - frontman_github_repo_url is string
      - frontman_github_branch is string

- name: Ensure frontman_users is defined correctly
  include_tasks: tasks/assert-users.yml
  vars:
    users: "{{ frontman_users }}"

- name: Ensure frontman_configs is defined correctly
  include_tasks: tasks/assert-configs.yml
  vars:
    configs: "{{ frontman_configs }}"

- name: Ensure frontman_servers is defined correctly
  include_tasks: tasks/assert-servers.yml
  vars:
    servers: "{{ frontman_servers }}"

- set_fact:
    frontman_static_root_local: "./{{ frontman_static_directory_filename }}"

- name: Initialize Git repository for GitHub Pages
  git:
    repo: "{{ frontman_github_repo_url }}"
    dest: "{{ frontman_static_root_local }}"
    version: "{{ frontman_github_branch }}"
    force: yes
  environment:
    GIT_TERMINAL_PROMPT: "0"

- name: Configure Git user for GitHub Pages deployment
  git_config:
    repo: "{{ frontman_static_root_local }}"
    scope: local
    name: user.name
    value: "Ansible Deployment"

- name: Configure Git email for GitHub Pages deployment
  git_config:
    repo: "{{ frontman_static_root_local }}"
    scope: local
    name: user.email
    value: "deployment@ansible.local"

- name: Create static directory locally
  file:
    path: "{{ frontman_static_root_local }}"
    state: directory

- name: Render index.html
  template:
    src: index.html.j2
    dest: "{{ frontman_static_root_local }}/index.html"

- name: Copy robots.txt
  copy:
    src: robots.txt
    dest: "{{ frontman_static_root_local }}/robots.txt"

- name: Render configs
  with_items: "{{ frontman_configs }}"
  loop_control:
    index_var: loop_index
  vars:
    frontman_config_uuid: "{{ item }}"
  include_tasks: render_configs.yml

- name: Render redirect configs
  with_items: "{{ frontman_users }}"
  loop_control:
    index_var: loop_index
  vars:
    frontman_user_uuid: "{{ item }}"
  template:
    src: frontend-link.json.j2
    dest: "{{ frontman_static_root_local }}/{{ frontman_user_uuid }}.json"

- name: Add all files to Git
  command: "git add ."
  args:
    chdir: "{{ frontman_static_root_local }}"

- name: Commit changes to Git
  command: "git commit -m 'Deploy static files for GitHub Pages - {{ ansible_date_time.iso8601 }}'"
  args:
    chdir: "{{ frontman_static_root_local }}"

- name: Push to GitHub repository
  command: "git push origin"
  args:
    chdir: "{{ frontman_static_root_local }}"
