- name: Fetch users UUIDs from Supabase
  delegate_to: localhost
  uri:
    url: "{{ config_supabase_project_url }}/rest/v1/users?select=child_uuid"
    method: GET
    headers:
      apikey: "{{ config_supabase_secret_api_key }}"
      Authorization: "Bearer {{ config_supabase_secret_api_key }}"
  register: supabase_users_response

- name: Set user UUIDs fact
  delegate_to: localhost
  set_fact:
    config_local_users: "{{ supabase_users_response.json | map(attribute='child_uuid') | list }}"
