- name: Fetch configs UUIDs from Supabase
  delegate_to: localhost
  uri:
    url: "{{ config_supabase_project_url }}/rest/v1/configs?select=uuid"
    method: GET
    headers:
      apikey: "{{ config_supabase_secret_api_key }}"
      Authorization: "Bearer {{ config_supabase_secret_api_key }}"
  register: supabase_configs_response

- name: Set user UUIDs fact
  delegate_to: localhost
  set_fact:
    config_local_configs: "{{ supabase_configs_response.json | map(attribute='uuid') | list }}"
