# title users should we when open hiddify
config_users_title:

# url where frontman is hosted
config_users_base_url:

# github repository URL for pages deployment (e.g., https://github.com/owner/repo.git)
# make sure the repository is PRIVATE and has GitHub Pages enabled
config_frontman_github_repo_url:

# github branch to deploy to (usually 'main' or 'gh-pages')
config_frontman_github_branch:

# url origin of personal portal
config_frontman_my_origin:
