config_servers:
  server1-uuid:
    # name of server (one line)
    name:
    # domain of server that will be put into config (IP or domain users will connect to)
    host:
    # ip address xray server should listen to. leave blank to listen all IP addresses
    inbound_ip:
    # ip address xray server should use for outbound connections. leave blank to use default (on OS level) IP address
    outbound_ip:
    # port of xray to be exposed and used publicly
    port:
    # flow parameter in https://xtls.github.io/en/config/outbounds/vless.html#serverobject (ideally xtls-rprx-vision)
    flow:
    # fingerprint parameters as `fingerprint` in https://xtls.github.io/ru/config/transport.html#tlsobject
    fingerprints:
      - chrome
      - safari
      - "..."
    # private key. generate with ./xray x25519
    private_key:
    # public key. generate with ./xray x25519
    public_key:
    # where regular https requests proxy to and what website xray should pretent as
    fallback_proxy_target: example.com
    # list of sni should be accepter by xray. see serverNames in https://xtls.github.io/ru/config/transport.html#realityobject
    supported_snis:
      - example.com
      - www.example.com
    prometheus_metrics:
      # port where prometheus metrics endpoints should be exposed
      port:
      # self-signed cert and keys SSL
      # generate with `openssl req -x509 -newkey rsa:4096 -keyout key.pem -out cert.pem -days 3650 -nodes -subj "/CN=<ip or domain value>" -addext "subjectAltName=<IP or DNS>:<ip or domain value>"`
      tls:
        certificate: |
            -----BEGIN CERTIFICATE-----
            ....
            -----END CERTIFICATE-----
        key: |
            -----BEGIN PRIVATE KEY-----
            ....
            -----END PRIVATE KEY-----
      # there are two APIs: for xray metrics and node_exporter metrics
      xray:
        # URL path (any string starting with /)
        url_path: /some-random-string1
      node_exporter:
        url_path: /some-random-string2

  # second server (for instance)
  server2-uuid:
    # name of server (one line)
    name:
    # domain of server that will be put into config (IP or domain users will connect to)
    host:
    # ip address xray server should listen to. leave blank to listen all IP addresses
    inbound_ip:
    # ip address xray server should use for outbound connections. leave blank to use default (on OS level) IP address
    outbound_ip:
    # port of xray to be exposed and used publicly
    port:
    # flow parameter in https://xtls.github.io/en/config/outbounds/vless.html#serverobject (ideally xtls-rprx-vision)
    flow:
    # fingerprint parameter in https://xtls.github.io/ru/config/transport.html#tlsobject
    fingerprints:
      -
      -
    # private key. generate with ./xray x25519
    private_key:
    # public key. generate with ./xray x25519
    public_key:
    # where regular https requests proxy to and what website xray should pretent as
    fallback_proxy_target:
    # list of sni should be accepter by xray. see serverNames in https://xtls.github.io/ru/config/transport.html#realityobject
    supported_snis:
      -
      -
    prometheus_metrics:
      # port where prometheus metrics endpoints should be exposed
      port:
      # self-signed cert and keys SSL
      # generate with `openssl req -x509 -newkey rsa:4096 -keyout key.pem -out cert.pem -days 3650 -nodes -subj "/CN=<ip or domain value>" -addext "subjectAltName=<IP or DNS>:<ip or domain value>"`
      tls:
        certificate:
        key:
      # there are two APIs: for xray metrics and node_exporter metrics
      xray:
        # URL path (any string starting with /)
        url_path:
      node_exporter:
        url_path:
