name: CD | Production

concurrency:
  group: master
  cancel-in-progress: false

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  deploy-proxies:
    name: Deploy on production
    uses: ./.github/workflows/CD-production-task.yml
    strategy:
      matrix:
        task:
          - deploy_metrics
          - deploy_proxies
          - deploy_frontman
    with:
      tasks: ${{ matrix.task }}
    secrets: inherit
