name: CD | Production

concurrency:
  group: master
  cancel-in-progress: false

on:
  push:
    branches:
      - master
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  deploy-proxies:
    name: Deploy on production
    uses: ./.github/workflows/CD-production-task.yml
    strategy:
      matrix:
        task:
          - deploy_metrics
          - deploy_proxies
    with:
      tasks: ${{ matrix.task }}
    secrets: inherit

  deploy-frontman:
    name: Deploy on production
    uses: ./.github/workflows/CD-production-frontman.yml
    secrets: inherit
